micronaut:
    application:
        name: geometryDeathBE
    security:
        enabled: true
        intercept-url-map:
            -   pattern: /api/auth/**
                access:
                    - isAnonymous()
#        authentication: bearer
#        token:
#            jwt:
#                signatures:
#                    secret:
#                        generator:
#                            secret: "${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"

datasources:
    default:
        url: ${datasources.default.url}
        username: ${datasources.default.username}
        password: ${datasources.default.password}
        driver-class-name: org.postgresql.Driver

jpa:
    hibernate:
        ddl-auto: none
    show-sql: false
    properties:
        hibernate:
            format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logger:
    levels:
        root: DEBUG
