version: "3.9"
services:
    postgres:
        image: postgres:15.3
        environment:
            POSTGRES_DB: "geometry_death_db"
            POSTGRES_USER: "root_aidar"
            POSTGRES_PASSWORD: "asdf"
        volumes:
            - .:/docker-entrypoint-initdb.d
        ports:
            - "5432:5432"